### ISSUE TITLE
Unable to connect to renderer error when using the app with Layouts Service

### ISSUE THREAD

**Issue by mustafakosker** [openfin/hello-openfin-selenium-example#7]
We initialized our test repo based on this example project. However, whenever we add layouts service to application manifest file, we're getting `Unable to connect to renderer` error when we call `getTitle` method on newly opened application. Do you know any workaround solution to get rid of this problem?

Here's the code piece that switches between windows by looking at their title:

    const tabs = await global.browser.windowHandles();

    for (const tab of tabs.value) {
      await global.browser.switchTab(tab);

      const title = await global.browser.getTitle(); // Fails on this line for 
                                                     //the newly opened app with layout service

      if (title.match(windowTitle)) {
        return tab;
      }
     }

Here's the error log:

Promise was rejected with the following reason: disconnected: unable to connect to renderer

      Error: Promise was rejected with the following reason: disconnected: unable to connect to renderer
    at window("CDwindow-af6e79b9-6aba-4c5c-9e40-cc5ee0917910") - switchTab.js:28:21
    at switchTab("CDwindow-af6e79b9-6aba-4c5c-9e40-cc5ee0917910") - index.js:237:23
    at title() - getTitle.js:31:28

**Comment by wenjunche** [comment]
Hello

Thank you for reporting the issue.

Few days ago, I made some changes to address the same issue you are having.  You need to 

1.  add the following to your app.json
            "devtools_port": 9090,

2.  add debuggerAddress to chromeOptions when initializing chromedriver in your test code:

      chromeOptions: {
                ...
                debuggerAddress: 'localhost:9090'
            }

3. get the latest RunOpenFin.bat from the repo

Please let us know if you have any questions.

Thanks

**Comment by mustafakosker** [comment]
Hi,

Thanks for your reply. I tried but it didn't work. This is about OpenFin Layout Services that we added recently to the project. I think OpenFin creates the window in a different way whenever we enable layouts in app.json.

**Comment by wenjunche** [comment]
Hello

Can you enable verbose logging of ChromeDriver and send me the log, content of your app.json and RunOpenFin.bat ?

Thanks

**Comment by mike-d-davydov** [comment]
We are having the same issue. Particular windows can't be interacted with by chromedriver (while others work just fine).

**Comment by mike-d-davydov** [comment]
Was able to fix the issue by following instruction above (changing devtools_port / debuggingAddress). Please update OpenFin.bat comments (they currently state that you should NOT set the devtools_port in app.json). Also had to update version of hadouken-js-adapter we were using to install our application to the latest one.

**Comment by wenjunche** [comment]
Hello

Thank you for the comments.   I have updated RunOpenFin.bat.
